// Deterministic PRD §7 test vectors from packages/sdk/src/math.ts, for the Rust math unit
// tests to load and match exactly (invariant I12). Values are decimal strings (u64 range).
import { duelResult, finalValue, payout, swapQuote } from "@rug-royale/sdk";
import { rng } from "./rng";

export const VECTORS_SEED = 12;
const U64_MAX = 2n ** 64n - 1n;

export function generateMathVectors() {
  const g = rng(VECTORS_SEED);
  const s = (v: bigint) => v.toString();

  // Reserves span demo-sized pools up to ~1e18 to exercise the u128 intermediates.
  const reserve = () =>
    g.pick([
      g.big(1n, 1_000n),
      g.big(1_000_000n, 10n ** 13n),
      g.big(10n ** 15n, 10n ** 18n),
    ]);

  const swaps = [];
  for (let i = 0; i < 500; i++) {
    const side = g.pick(["buy", "sell"] as const);
    const r = { quoteReserve: reserve(), tokenReserve: reserve() };
    const src = side === "buy" ? r.quoteReserve : r.tokenReserve;
    // Keep reserve + amount_in inside u64, as the program's u64 reserves require.
    const amountIn = g.big(
      1n,
      src * 3n < U64_MAX - src ? src * 3n : U64_MAX - src
    );
    const fee = g.pick([0, 30, 100, 1000]);
    const q = swapQuote(side, amountIn, r, fee);
    swaps.push({
      side,
      amount_in: s(amountIn),
      quote_reserve: s(r.quoteReserve),
      token_reserve: s(r.tokenReserve),
      fee_bps: fee,
      out: s(q.out),
      quote_reserve_after: s(q.quoteReserve),
      token_reserve_after: s(q.tokenReserve),
    });
  }

  // Edge cases: dust that rounds to zero output (ZeroOutput), fee-only input, huge reserves.
  const edges: ["buy" | "sell", bigint, bigint, bigint, number][] = [
    ["buy", 1n, 10n ** 12n, 10n ** 12n, 30],
    ["sell", 1n, 10n ** 12n, 10n ** 12n, 30],
    ["buy", 9n, 10n ** 6n, 10n ** 6n, 1000],
    ["buy", 1n, 1n, 1n, 0],
    ["sell", 10n ** 18n, 10n ** 18n, 10n ** 18n, 30],
  ];
  for (const [side, amountIn, qr, tr, fee] of edges) {
    const q = swapQuote(
      side,
      amountIn,
      { quoteReserve: qr, tokenReserve: tr },
      fee
    );
    swaps.push({
      side,
      amount_in: s(amountIn),
      quote_reserve: s(qr),
      token_reserve: s(tr),
      fee_bps: fee,
      out: s(q.out),
      quote_reserve_after: s(q.quoteReserve),
      token_reserve_after: s(q.tokenReserve),
    });
  }

  const valuations = [];
  for (let i = 0; i < 100; i++) {
    const r = {
      quoteReserve: g.big(1_000_000n, 10n ** 13n),
      tokenReserve: g.big(1_000_000n, 10n ** 13n),
    };
    const quoteVault = g.big(0n, 10n ** 12n);
    const coinVault = g.pick([0n, g.big(1n, 10n ** 12n)]);
    const fee = g.pick([0, 30, 100]);
    valuations.push({
      quote_vault: s(quoteVault),
      coin_vault: s(coinVault),
      quote_reserve: s(r.quoteReserve),
      token_reserve: s(r.tokenReserve),
      fee_bps: fee,
      value: s(finalValue(quoteVault, coinVault, r, fee)),
    });
  }

  const results = [];
  for (let i = 0; i < 50; i++) {
    const a = g.big(0n, 10n ** 12n);
    const b = g.pick([a, g.big(0n, 10n ** 12n)]);
    results.push({ final_a: s(a), final_b: s(b), result: duelResult(a, b) });
  }

  const payouts = [];
  for (let i = 0; i < 200; i++) {
    const args = {
      entryLamports: g.pick([0n, g.big(1n, 1_000_000_000n)]),
      sponsoredLamports: g.pick([0n, g.big(1n, 2_000_000_000n)]),
      settlerTipLamports: g.big(0n, 5_000_000n),
      rakeBps: g.int(0, 1000),
      result: g.pick([1, 2, 3] as const),
    };
    const p = payout(args);
    payouts.push({
      entry_lamports: s(args.entryLamports),
      sponsored_lamports: s(args.sponsoredLamports),
      settler_tip_lamports: s(args.settlerTipLamports),
      rake_bps: args.rakeBps,
      result: args.result,
      pot: s(p.pot),
      rake: s(p.rake),
      tip: s(p.tip),
      prize: s(p.prize),
      to_creator: s(p.toCreator),
      to_opponent: s(p.toOpponent),
      to_treasury: s(p.toTreasury),
      to_settler: s(p.toSettler),
    });
  }

  return {
    _about:
      "Generated by `pnpm math:vectors` from packages/sdk/src/math.ts (PRD §7). Rust math must reproduce every case exactly (I12). Do not edit by hand.",
    seed: VECTORS_SEED,
    swaps,
    valuations,
    results,
    payouts,
  };
}

export const MATH_VECTORS_PATH = "programs/rug_royale/tests/vectors/math.json";
